### ISSUE TITLE
No new races appear in the client

### ISSUE THREAD

**Issue by NiganNi** [benjymansy123/mod-worgoblin#1]
Hi benjymansy123 I copy your patch-A.MPQ to the Date folder but didn't get the desired result. There are still no goblins or worgen.
I get my way ..\Data\patch-4.MPQ why is the change not being applied to the client?

**Comment by benjymansy123** [comment]
Could be any number of things, I don't guarantee that this works with anything other than an enUS client because I don't have any other client to test with, I don't think it could be an unpatched executable, but it's not impossible. Could also be that you need to delete your Cache folder.

**Comment by NiganNi** [comment]
I have already tried everything, there are no new races. But if I change the existing races to new ones, as described here ( https://model-changing.net/files/file/202-sethrak-for-draenei-female-and-malewow-335a/ ), then I will not have problems with displaying.

**Comment by NiganNi** [comment]
Downloaded a clean ENIS client, put the patch in the \Data folder, but I still have no changes, what could be wrong, help me figure it out?

**Comment by benjymansy123** [comment]
Have you patched your Wow executable?

**Comment by NiganNi** [comment]
No, I thought to just throw it off as with hd-models. What should I patch the wow.exe?

**Comment by NiganNi** [comment]
Thank you very much, I realized my mistake!
