### ISSUE TITLE
Corpse model

### ISSUE THREAD

**Issue by benjymansy123** [benjymansy123/mod-worgoblin#11]
Currently when a player dies, their character's body lies on the ground until they resurrect (Either at the spirit healer or at the body.) Once the player resurrects, the model changes to a skeleton and after a certain time, that model despawns. Currently, the worgen (Likely the goblins too, haven't tested though) have the unused blue/white grid box in lieu of the skeleton model. This needs to be fixed, though I don't know how I would do that at this point.

**Comment by NiganNi** [comment]
Yes, goblins do the same, and blood elves do a good job. I assume the absence of a skeleton model in the patch-A file
![2022-03-10_14-11-55](https://user-images.githubusercontent.com/61392055/157650584-1664aa47-49d2-4468-bfa7-73a5a0386a1f.png)
![2022-03-10_14-12-26](https://user-images.githubusercontent.com/61392055/157650599-87682069-8e9d-45a8-ad45-77c307d0c815.png)
![2022-03-10_14-15-45](https://user-images.githubusercontent.com/61392055/157651027-b4433b8a-5241-4e95-9589-2b9b8c3c545b.png)

**Comment by benjymansy123** [comment]
Okay, I've determined that the corpse models for each race are stored in /World/GENERIC/PASSIVEDOODADS/DEATHSKELETONS/ and look to be declared in GameObjectDisplayInfo.dbc, but I don't see the connection between that file and each race getting their skeletons.

**Comment by benjymansy123** [comment]
Alright, I found this on the WoW Modding Discord from schlumpf#6709:

> World\Generic\PassiveDoodads\DeathSkeletons\<Race><Gender>DeathSkeleton.m2 where Race comes from ChrRaces::m_ClientPrefix.

**Comment by benjymansy123** [comment]
[Data.zip](https://github.com/benjymansy123/mod-worgoblin/files/8405209/Data.zip)
Here's the corpse models that _should_ be 3.3.5 compatible for both goblin and worgen if someone wants to experiment, as I need to deal with my organization for my wow files.

**Comment by benjymansy123** [comment]
Should be resolved with https://github.com/benjymansy123/mod-worgoblin/commit/316debe8d967d0746f43956172a47232d5d6bfab, please reopen the issue if the problem persists.

**Comment by benjymansy123** [comment]
Still an issue for goblins, working for worgen though.

**Comment by benjymansy123** [comment]
Okay, should be entirely fixed with https://github.com/benjymansy123/mod-worgoblin/commit/4599681aa805ebf6967a751dbdd88819e7aa1b9d now. Promise.

**Comment by Blandyoung** [comment]
Great help, brother Thank you
