### ISSUE TITLE
TODO: Fix the borders of the icons.

### ISSUE THREAD

**Issue by benjymansy123** [benjymansy123/mod-worgoblin#19]
Darn you, Kitzunu.

**Comment by Kitzunu** [comment]
<3

**Comment by benjymansy123** [comment]
Resolved with https://github.com/benjymansy123/mod-worgoblin/commit/dc071c8724e1aa51486097fc9d0eebc2e4208dcd and https://github.com/benjymansy123/mod-worgoblin/commit/3f309dc89f0b0f2bb3d76b39772806ced391f6a7. Many thanks Kitzunu for the icons provided :D
