### ISSUE TITLE
Mac patch not functional

### ISSUE THREAD

**Issue by Sifl46** [benjymansy123/mod-worgoblin#20]
Hey, I happen to be a Mac user who was interested in this mod about as soon as the "Mac patch" was commited.
I gave it a go with the .app provided, and was given this error.
https://puu.sh/J6NcB/76cf4432cc.png

I tested the windows patched exe via wine, and confirmed it worked correctly with that client.

**Comment by benjymansy123** [comment]
Currently investigating this, still haven't gotten around to testing on my own Mac, but I'm hunting around for other patches. Might end up patching it myself and distributing it here.

**Comment by benjymansy123** [comment]
Okay, getting the same issue on my MacBook, just gonna try to patch it myself.

**Comment by benjymansy123** [comment]
Sorry for the delay @Sifl46, but a patched .app file is now listed on the readme. I did test it and it did work for me, so I'm going to close this issue. Let me know if you have any other issues, of course!
