### ISSUE TITLE
Missing Death Knight Blood Talent tree with Worgen/Goblin

### ISSUE THREAD

**Issue by Sifl46** [benjymansy123/mod-worgoblin#23]
The blood talent tree doesn't show at all when making a Worgen or Goblin Death Knight. Frost and Unholy show up fine. Blood also shows up normally with any other race.

I didn't have time to see if this happens with any other class other than Death Knight.

**Comment by benjymansy123** [comment]
Unless I tested incorrectly, it looks like the Death Knight's blood tree is the only one affected in terms of worgen, will test the goblins after I fix this. Thank you for the report!
