### ISSUE TITLE
wonderful!

### ISSUE THREAD

**Issue by Helias** [benjymansy123/mod-worgoblin#4]
add this to the azerothcore catalogue adding the github-topic "azerothcore-module"

**Comment by benjymansy123** [comment]
https://github.com/azerothcore/azerothcore.github.io/pull/64

Don't know if there's anything I'm missing there that I should be including or doing differently, but there it is.

**Comment by benjymansy123** [comment]
https://www.azerothcore.org/catalogue.html#/details/442338662

:D
